version: "3"

services:
  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env
    expose:
      - ${REDIS_PORT}
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    expose:
      - ${MYSQL_PORT}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    restart: always
    expose:
      - ${APP_PORT}
    depends_on:
      mysql:
        condition: service_healthy
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host ${APP_HOST} --port ${APP_PORT}"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - fastapi
    ports:
      - ${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}
      - ${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network


networks:
  app-network:
    driver: "bridge"
