services:
  redis:
    container_name: redis
    image: redis:8.0-M02-bookworm
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    depends_on:
      redis:
        condition: service_healthy

  s3:
    container_name: s3
    image: localstack/localstack:latest
    ports:
      - ${GATEWAY_LISTEN}:${GATEWAY_LISTEN}
    volumes:
      - localstack-data:/var/lib/localstack
    env_file:
      - .env
#    depends_on:
#      postgres:
#        condition: service_healthy

  backend:
    container_name: backend
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host ${APP_HOST} --port ${APP_PORT}"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  localstack-data:


